###
GET http://localhost:9000/api/v1/users HTTP/1.1

###
POST http://localhost:9000/api/v1/users HTTP/1.1
Content-Type: application/json

{
    "username": "aguspa",
    "password": "7663",
    "mail": "aguspa@gmail.com"
}

###
PUT http://localhost:9000/api/v1/users/25 HTTP/1.1
Content-Type: application/json

{
    "mail": "aguspaezre@gmail.com"
}

###
DELETE http://localhost:9000/api/v1/users/23 HTTP/1.1